### ISSUE TITLE
Yahoo is not allow to download the stock data.

### ISSUE THREAD

**Issue by mallick84** [prodipta/gquote#1]
Yahoo is not allowed to connect with the web-link site, that you have mentioned in this coding. so is there any alternate site that i can replace it with and run your code? please suggest me.

**Comment by prodipta** [comment]
Unfortunately, both yahoo and google have stopped supporting intraday data dissemination. I think at present, there are not much other options apart from going for a paid source.

**Comment by mallick84** [comment]
i am extreamly sorry that I could not make a response on your reply. Thank
you for your response. i got it.

Actually I am trying to make forecasting for predicting any
equipment/machine breakdown on real time data like technical parameter such
as vibration, temperature and etc, which I extract from my plant SQL server
and do forecasting on R shiny with good visualisation.

i am already on process. If you have any similar link  as my support
studies, could help me a lot.

Anyway, once again thank you.

Avijit Mallick.
